name: radada
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - matplotlib 
  - omegaconf
  - fvcore
  - iopath
  - tqdm
  - pandas
  - scikit-learn
  - jupyter
  - pip
  - pip:
    - numpy
    - mne
    - seaborn
    - openpyxl
    - lightgbm
    - statsmodels

